### ISSUE TITLE
[Bug] Can't get in a server

### ISSUE THREAD

**Issue by HydrogenC** [faceofcat/Tesla-Powered-Thingies#46]
It turned "Not responding" when I tried to enter my server with Tesla-Powered-Thingies. 
After I removed your mod, it worked well. It didn't respond so I have to terminate it manually. 
Here's the part of the log: 
`
[20:38:40] [Session-Validator/INFO]: Session validation failed: Invalid token
[20:38:42] [Server Connector #1/ERROR]: Couldn't connect to server
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:25565
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_172]
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source) ~[?:1.8.0_172]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:352) ~[NioSocketChannel.class:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[AbstractNioChannel$AbstractNioUnsafe.class:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:612) ~[NioEventLoop.class:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) ~[NioEventLoop.class:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) ~[NioEventLoop.class:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) ~[NioEventLoop.class:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[SingleThreadEventExecutor$5.class:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_172]
Caused by: java.net.ConnectException: Connection refused: no further information
	... 10 more
[20:40:59] [main/INFO]: Connecting to localhost, 25565
[20:40:59] [Netty Client IO #1/INFO]: Generating new Event Handler Proxy Class com.mumfrey.liteloader.core.event.EventProxy
[20:40:59] [Netty Client IO #1/INFO]: Successfully generated event handler proxy class with 124 handlers(s) and 124 total invocations
[20:40:59] [Netty Client IO #1/INFO]: Baking listener list for PostLoginListener with 0 listeners
[20:40:59] [Netty Client IO #1/INFO]: Server protocol version 2
[20:41:00] [Netty Client IO #1/INFO]: Attempting connection with missing mods [waila, jeiintegration, mousetweaks, timehud, wailaharvestability, reauth] at SERVER
[20:41:00] [main/INFO]: Injecting existing registry data into this client instance
[20:41:00] [main/INFO]: Registry IncineratorRecipe: Found a missing id from the world teslathingies:minecraft_spruce_fence_gate
[20:41:00] [main/INFO]: Registry IncineratorRecipe: Found a missing id from the world teslathingies:minecraft_dark_oak_fence_gate
[20:41:00] [main/INFO]: Registry IncineratorRecipe: Found a missing id from the world teslathingies:minecraft_jungle_fence_gate
[20:41:00] [main/INFO]: Registry IncineratorRecipe: Found a missing id from the world teslathingies:minecraft_acacia_fence_gate
[20:41:00] [main/INFO]: Registry IncineratorRecipe: Found a missing id from the world teslathingies:minecraft_birch_fence_gate
[20:41:00] [main/INFO]: Registry IncineratorRecipe: Found a missing id from the world teslathingies:minecraft_fence_gate
[20:41:00] [main/ERROR]: Unidentified mapping from registry teslathingies:incinerator_recipes
[20:41:00] [main/ERROR]:     teslathingies:minecraft_dark_oak_fence_gate: 18
[20:41:00] [main/ERROR]:     teslathingies:minecraft_birch_fence_gate: 14
[20:41:00] [main/ERROR]:     teslathingies:minecraft_jungle_fence_gate: 15
[20:41:00] [main/ERROR]:     teslathingies:minecraft_fence_gate: 16
[20:41:00] [main/ERROR]:     teslathingies:minecraft_acacia_fence_gate: 13
[20:41:00] [main/ERROR]:     teslathingies:minecraft_spruce_fence_gate: 17
[20:41:00] [main/ERROR]: Network Disconnect: Fatally missing registry entries
`

**Comment by faceofcat** [comment]
was there any change done to any other mod prior to this?... seems server-side had different registries than client-side... :|

**Comment by HydrogenC** [comment]
I found the problem. I installed [Malisis Doors](https://minecraft.curseforge.com/projects/malisisdoors) which overrides the vanilla fence doors. Your mod also override fence doors, so the conflict happen. By the way, why are your mod overriding vanilla fence doors?

**Comment by faceofcat** [comment]
I'm not... but... I "copy" them for the incinerator... which burns them for energy... or something... and that might happen before malisis does it's stuff... :|... weird.
